### ISSUE TITLE
Workerman broadcast

### ISSUE THREAD

**Issue by Vitalicus** [walkor/workerman#901]
My old code was like this

```
<?php
class SocketService
{
    private $connections;
    private $worker;
    public function run(){

        $context = array(
            'ssl'=>array(
            'local_cert'=>'/var/www/mysite.com/SSL/cert.pem',
            'local_pk'=>'/var/www/mysite.com/SSL/privkey.pem',
            'verify_peer'=>false,
            )
        );

        $this->worker = new \Workerman\Worker('websocket://mysite.com:888',$context);
        $this->worker->transport='ssl';
        $this->worker->count=40;
        $this->worker->onConnect = function($connection){
            $connection->onWebSocketConnect = function ($connection,$header){
            $this->connections[$_GET['userId']] = $connection;    
                dump(array_keys($this->connections));
            };
        };

        $this->worker->onMessage = function ($connection,$data) {
            dump(count($this->connections));
            foreach ($this->connections as $key => $connection) {
                dump('send message to user: ' . $key);
                $connection->send($data);
            }
        };
        \Workerman\Worker::runAll();
    }
}
```

In this version I can't get userID and send data to all users :(. 
Please help

**Comment by joanhey** [comment]
The v4 (and up) don't use superglobals ($_GET, $_POST, ...).
Now uses a Request object, so to get the userID, you need to change `$_GET['userId']` to `Request->get('userID')`. And pass the `Request` in the `onConnect`.


Before:
```php
$this->worker->onConnect = function($connection){
            $connection->onWebSocketConnect = function ($connection,$header){
            $this->connections[$_GET['userId']] = $connection;    
                dump(array_keys($this->connections));
            };
        };

```

Now:
```php
$this->worker->onConnect = function($connection, $request) {
            $connection->onWebSocketConnect = function ($connection, $header){
            $this->connections[$request->get(['userId')] = $connection;    
                dump(array_keys($this->connections));
            };
        };
```

**Comment by Vitalicus** [comment]
I want to do this code without classand I try your code:

`$ws_worker->onConnect = function($connection,$request) {
    $connection->onWebSocketConnect = function ($connection, $header){
    $connections[$request->get('userId')] = $connection;    
        var_dump(array_keys($connections));
    };
};`

But recive a error:
`ArgumentCountError: Too few arguments to function {closure}()`

**Comment by fuzqing** [comment]
Your code works fine on V4.1, please check your current version.
You can see [about-websocket](https://www.workerman.net/doc/workerman/appendices/about-websocket.html)

**Comment by xpader** [comment]
@joanhey Does v5 support superglobals?
How does same superglobal keep in same async callback context?
I mean superglobal cross the whole process, but multiple async callback running sametime in one process.

**Comment by joanhey** [comment]
Workerman v4 and v5 don't use superglobals.
Because some event systems, use threads, and it's not possible use it with superglobals.

But you can use Adapterman:
https://github.com/joanhey/AdapterMan
that always will work with superglobals, with the event systems that permit it. (event php, event lib, ev, ...)

**Comment by eusonlito** [comment]
Hello @joanhey, but `$this->worker->onConnect` to `websockets` don't include the second parameter `$request`, you only get the first one `$connection`, no?

**Comment by Vitalicus** [comment]
@joanhey Tell me please, how to do foreach. Send recived data for each client

**Comment by walkor** [comment]
Workerman V5

```
<?php
class SocketService
{
    private $connections;
    private $worker;
    public function run(){

        $context = array(
            'ssl'=>array(
            'local_cert'=>'/var/www/mysite.com/SSL/cert.pem',
            'local_pk'=>'/var/www/mysite.com/SSL/privkey.pem',
            'verify_peer'=>false,
            )
        );

        $this->worker = new \Workerman\Worker('websocket://mysite.com:888',$context);
        $this->worker->transport='ssl';
        $this->worker->count=40;
        $this->worker->onConnect = function($connection){
            $connection->onWebSocketConnect = function ($connection, $request){
                $this->connections[$request->get('userId')] = $connection;    
                dump(array_keys($this->connections));
            };
        };

        $this->worker->onMessage = function ($connection,$data) {
            dump(count($this->connections));
            foreach ($this->connections as $key => $connection) {
                dump('send message to user: ' . $key);
                $connection->send($data);
            }
        };
        \Workerman\Worker::runAll();
    }
}
```

**Comment by shizzic** [comment]
@walkor Hi!
1) Is there a possability to use your example, but with multiple processes (if there is any, can you share)? Or i doomed to use only one process if i wanna make it work within class?
2) Will i be able to get connections inside another method in the class?

**Comment by walkor** [comment]
1. No
2. No
3. v4 is enough

A single process of Workerman is capable of handling over 10,000 connections, which is sufficient for the majority of business needs.

Here is an example for multiple processes broadcast.
https://www.workerman.net/doc/workerman/components/channel-examples2.html

And this is an example for multiple server and  processes broadcast.
https://www.workerman.net/doc/workerman/components/channel-examples.html
